# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af727351bca48b0005ec6ce8933dba339cb52a2295e5096cafbd739f22d475ecde63daf5e1893ec63d440a42dfb4e2cf8ea11f34c9dbb8db82b973c0c2bb5ea5

test:
  secret_key_base: a24ff20c9e190a8e9743a531f6995b462388ccb7be86e7206367c2049520e031441cef1cfe790dd174bcc6a64f09f7b401a4db7aac487949a6007cc9d72037ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
